### ISSUE TITLE
Compile error!

### ISSUE THREAD

**Issue by bumpz** [n0ise9914/RdpChecker#3]
There are multiple error can you give instructions for compiling?

**Comment by n0ise9914** [comment]
Send me output of errors to help you!

**Comment by bumpz** [comment]
Hello , 

there are 11 of total errors i'll paste it on 

https://pastebin.com/nCVLZRfQ  

Thank you.

**Comment by n0ise9914** [comment]
Hi,

i have checked out the output, the issue comes from missing reference to essential libraries.

you should import these two essential libraries: AxInterop.MSTSCLib and Interop.MSTSCLib

right-click on the project and select Add > Reference > COM tab
then import AxMsRdpClient8NotSafeForScripting
